### ISSUE TITLE
Infinite UAC prompts

### ISSUE THREAD

**Issue by aplum** [zerotier/DesktopUI#15]
When opening ZeroTier UI for the first time on a Windows account, the UAC prompt cannot be dismissed by clicking "No" – it keeps popping up again every time it's dismissed. The easiest way to escape seems to be locking the PC (Win+L) and restarting.

Expected behaviour is that the action will be cancelled and it will not ask again.

UAC prompt's Program location: "C:\Program Files (x86)\ZeroTier\One\zerotier_desktop_ui.exe" copy_authtoken
ZeroTier 1.8.4
Windows 10

**Comment by BorysekOndrej** [comment]
I second this. I am unable to open ZeroTier GUI in Windows under a user with standard privileges.

Steps to reproduce:
1. Download ZeroTier installation file for Windows (tested with 1.8.4)
2. Start the installation
3. Click Yes in the UAC dialog (Do you want to allow this app to make changes to your device; "C:\Program Files (x86)\ZeroTier\One\zerotier_desktop_ui.exe" copy_authtoken)

Expected behavior:
The GUI starts after a single UAC dialog.

Actual behavior:
Infinite loop in step 3.

I've also tried installation under admin account, that went alright. Then, when I switched to the regular user and tried to start the GUI, the same UAC dialog with infinite loop reappeared.

Starting or stopping the ZeroTier service does not appear to make a difference.

OS: Windows 10 - up to date, 21H2 (build 19044.1348)

This might not be a new error, similar behavior was mentioned in 2019. zerotier/ZeroTierOne/issues/1083

**Comment by aplum** [comment]
@BorysekOndrej The fact that you can't open the GUI as a non-admin user is expected and desired. A non-admin user can only open the GUI if admin credentials are provided at the UAC prompt – after this has been done once, they will be able to open it again in the future without requiring admin credentials again (someone correct me if I'm wrong, I can't find the post I've seen explaining the authtoken).

But yes, we are encountering the same issue that it continually prompts until it receives admin credentials and won't take no for an answer.

**Comment by BorysekOndrej** [comment]
Hi, thank you for the incredibly quick response. I understand that requiring admin credentials might be desired/required. The problem I am encountering is not just that it does not take No for an answer, but that it also loop when I provide correct admin credentials. I apologize if that wasn't clear from my post.

**Comment by aplum** [comment]
Ah, yes that was not clear that you were providing admin credentials. I haven't tested that in a while, but I'll try opening it as a standard user tomorrow and see if I have the same issue.

**Comment by aplum** [comment]
In the meantime, have you tried deleting `%localappdata%\ZeroTier\authtoken.secret` in the standard user's account, then trying to open the GUI again?

**Comment by BorysekOndrej** [comment]
The folder `%localappdata%\ZeroTier` gets created for the standard user, but it's empty. The file `authtoken.secret` is repeatedly written to the admins account folder.

**Comment by BorysekOndrej** [comment]
Manually copying it to the standard users folder seems to fix the problem (at least it allows to open the control panel). I'll check if anything else is broken. In meantime - thank you very much for the pointers to the workaround. 👍

**Comment by aplum** [comment]
@BorysekOndrej I just tested with a standard user and I'm seeing the same results you are. I thought this had worked before, but even running the installer from a standard user's account lead to the same result. Also tested with the original ZT version we started with, 1.8.1. Anyway, glad you have a workaround for now.

**Comment by tic680** [comment]
Ipromoted the user to admin, installed zero tier on their profile and then logged in as admin and downgraded the permissions again. it worked for me

**Comment by IlexPauc** [comment]
I've also been having this issue in production. The workaround does work, but it opens up the control panel to the user without needing admin credentials. For now, the workaround will be fine, but I worry about users messing with the configuration.

**Comment by cpuwolf** [comment]
it saves my life

**Comment by aplum** [comment]
@glimberg I just tested and this doesn't seem to be fixed. What _does_ seem to be fixed is:
- 1.8.6: Responding to UAC with no, no, no, no, yes -> still prompts infinitely after clicking "yes".
- 1.8.7: no, no, no, no, yes -> clicking "yes" does what it should, and the prompts stop.
 
But this really doesn't help our users who don't have admin rights and can't click yes. ZeroTier should stop prompting after the first "no".

**Comment by cpuwolf** [comment]
The installation includes the device driver, that its a key point that admin rights are required.

**Comment by aplum** [comment]
@cpuwolf This issue is about opening the ZeroTier UI, not installing ZeroTier. Although even if the discussion were about installing it, the core of the issue would remain the same – listen to the user when they tell you "no".
