### ISSUE TITLE
Error compiling on windows (x64)

### ISSUE THREAD

**Issue by wewlad-dev** [zerotier/DesktopUI#25]
Following the readme, when I compile it in Windows (x64) I get the following error (multiple errors from gimli)

`error[E0412]: cannot find type 'Option' in this scope--> C:\Users\user\Desktop\DesktopUI-master\vendor\gimli\src\read\mod.rs:653:55](http://mod.rs:653:55/)|653 | fn lookup_offset_id(&self, id: ReaderOffsetId) -> Option<(SectionId, R::Offset)>| ^^^^^^ not found in this scope`

**Comment by wewlad-dev** [comment]
Ok solved with `rustup target add i686-pc-windows-msvc ` it turned out I don't have core added. However, nether i686 or 64 will have the output in release folder only debug.

**Comment by erikh** [comment]
try this commandline instead:

```
cargo install --path . --release
```
