### ISSUE TITLE
1.8.6 Apple M1 Pro Waiting for ZeroTier system services...

### ISSUE THREAD

**Issue by CoderYLZhang** [zerotier/DesktopUI#30]
<img width="273" alt="image" src="https://user-images.githubusercontent.com/13221319/158060725-a445abcf-a547-460c-91bd-2dab64fceda5.png">

don't work after I uninstall and reinstall it.

zerotier-one 1.8.6, macOS 12.2.1

**Comment by adamierymenko** [comment]
It's also possible that you are experiencing a different problem. What happens if you type `sudo zerotier-cli status` in a terminal?

**Comment by CoderYLZhang** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/13221319/158213042-5a71b551-fa62-4977-951b-fea0cd66722c.png">

but there is something wrong here

**Comment by CoderYLZhang** [comment]
sudo zerotier-cli status                                       
401 status {}

**Comment by dec0dOS** [comment]
![Screenshot 2022-03-16 at 16 14 14](https://user-images.githubusercontent.com/14824142/158598415-dafbba4c-b0b3-4408-8e75-9f8934f49677.png)
Same problem here. ZeroTier works fine via zerotier-cli

**Comment by dec0dOS** [comment]
Any updates? I've reinstalled the ZeroTier several times.

**Comment by CoderYLZhang** [comment]
> Any updates? I've reinstalled the ZeroTier several times.

NO, 1.8.9 problems remain

**Comment by fengted** [comment]
Try to remove the directory "~/Library/Application Support/ZeroTier" after uninstall  Zerotier One and Zerotier App  using "/Library/Application Support/ZeroTier/One/uninstall.sh". Then reinstall Zeortier.

**Comment by fengted** [comment]
Or just quit Zerotier app, remove  "~/Library/Application Support/ZeroTier", re-launch Zerotier app.

**Comment by LockVer** [comment]
1.8.10 problems remain 
macos 12.3 m1

**Comment by LockVer** [comment]
> Or just quit Zerotier app, remove "~/Library/Application Support/ZeroTier", re-launch Zerotier app.

Not resolved

**Comment by FLIER001** [comment]
1.10 problem remain

**Comment by OrangeDou** [comment]
Try this command:
sudo /Library/Application\ Support/ZeroTier/One/launch.sh
and restart the zerotier app
![image](https://github.com/user-attachments/assets/42f7403b-6dc4-4d8c-877a-a369590c6211)
Resolved but i don't know why 
Zerotier 1.14.2 Mac os 15.0.1

**Comment by Jeffjeno** [comment]
(base) 192:One wangzhizhou$ sudo /Library/Application\ Support/ZeroTier/One/launch.sh
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
zerotier-one: fatal error: cannot bind to local control interface port 9993 
After I run

**Comment by OrangeDou** [comment]
> (base) 192:One wangzhizhou$ sudo /Library/Application\ Support/ZeroTier/One/launch.sh shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted zerotier-one: fatal error: cannot bind to local control interface port 9993 After I run

I see there are two errors:
1. a."Operation not permitted":Confirm you have access to the zerotier directory,and check zerotier working directory.
2. b."port 9993":Check if your port 9993 is  occupied,or you can change the zerotier config file to make it run on other port.The other is make sure your firewall doesn't prevent this port.

follow is the content of my "/Library/Application\ Support/ZeroTier/One/launch.sh":
`#!/bin/bash
export PATH="/Library/Application Support/ZeroTier/One:/bin:/usr/bin:/sbin:/usr/sbin"
/usr/bin/killall MacEthernetTapAgent >>/dev/null 2>&1
exec zerotier-one`
If there are any other errors,welcome to discuss.
