### ISSUE TITLE
issues while configure routes for zerotier network

### ISSUE THREAD

**Issue by machine-doll** [zerotier/DesktopUI#47]
<img width="231" alt="image" src="https://user-images.githubusercontent.com/87234334/219948431-6772576e-edd0-40e7-add8-440b132de2fa.png">
I have a nas in my home, and I installed zerotier on my router. The router has assigned IP `192.168.191.1`, and I set a route for it.  
Somehow I can't access my nas on my PC, but I can still access my nas on smartphone.    
<img width="816" alt="image" src="https://user-images.githubusercontent.com/87234334/219948785-6a579a86-cc7f-4ee3-b403-fe0d352c0d3c.png">
I can find the route in Windows on my PC, but there are some more routes.  
I tried pinging my NAS and router, my NAS didn't make any ICMP echo, but my router can send ICMP echo via IP `192.168.191.1`, and can't send ICMP echo via `192.168.50.1`  
I've checked Windows's fireware, and can't find any issue.

**Comment by laduke** [comment]
Hello,
commonly the issue is the NAS doesn't have a route back to the zerotier network. You can tell your zerotier "router" to masquerade. Or add the route to your LAN's default gateway if possible.
