### ISSUE TITLE
[Windows 10] Resize leaves black space around main UI

### ISSUE THREAD

**Issue by DarkArc** [zerotier/DesktopUI#6]
Resizing the UI window doesn't resize any of the contained elements.

![image](https://user-images.githubusercontent.com/778012/140236401-32fbd229-9fa8-41b2-ab37-ccb9d4032cbd.png)

I also tried this on a Mac, and things work as I'd expect there.

**Comment by lue30499** [comment]
I have this minor graphical issues as well.
Content isn't moving with the resize of the window.

**Comment by DarkArc** [comment]
I suspect this is irrelevant now as the web view has been removed; closing.
